#!/usr/bin/env python3
"""
NPTEL Notes Builder — Embeds all .md files into index.html
so it works when opened directly via file:// (no server needed).

Usage:
  python build.py

Run this whenever you add, rename, or remove lecture .md files.
It will:
  1. Scan all folders for .md files
  2. Update the FILE_TREE in index.html
  3. Embed all markdown content into index.html
"""

import os
import re
import json

ROOT = os.path.dirname(os.path.abspath(__file__))
INDEX = os.path.join(ROOT, 'index.html')


def find_md_files():
    """Scan for all .md files and return dict of relative_path -> content."""
    files = {}
    for dirpath, dirnames, filenames in os.walk(ROOT):
        # Skip hidden folders
        dirnames[:] = [d for d in dirnames if not d.startswith('.')]
        for f in sorted(filenames):
            if f.lower().endswith('.md'):
                full = os.path.join(dirpath, f)
                rel = os.path.relpath(full, ROOT).replace('\\', '/')
                with open(full, 'r', encoding='utf-8') as fh:
                    content = fh.read()
                if content.strip():  # skip empty files
                    files[rel] = content
    return files


def build_file_tree(md_files):
    """Build the FILE_TREE object from discovered files."""
    tree = {}
    for path in sorted(md_files.keys()):
        parts = path.split('/')
        if len(parts) >= 3:
            course = parts[0]
            folder = '/'.join(parts[1:-1])
            filename = parts[-1]
        elif len(parts) == 2:
            course = parts[0]
            folder = 'General'
            filename = parts[1]
        else:
            continue
        tree.setdefault(course, {}).setdefault(folder, []).append(filename)
    return tree


def build():
    md_files = find_md_files()
    if not md_files:
        print("No .md files found!")
        return

    file_tree = build_file_tree(md_files)

    with open(INDEX, 'r', encoding='utf-8') as f:
        html = f.read()

    # ── Build embedded <script type="text/x-markdown"> tags ──
    lines = []
    lines.append('  <!-- ═══ EMBEDDED MARKDOWN DATA (auto-generated by build.py) ═══ -->')
    for path, content in sorted(md_files.items()):
        # Escape </script> if it ever appears inside markdown
        safe = content.replace('</script>', '<\\/script>')
        lines.append(f'  <script type="text/x-markdown" data-path="{path}">')
        lines.append(safe)
        lines.append('  </script>')
    lines.append('  <!-- ═══ END EMBEDDED MARKDOWN DATA ═══ -->')
    embedded_block = '\n'.join(lines) + '\n'

    # ── Replace existing embedded block, or insert before main <script> ──
    marker_re = r'  <!-- ═══ EMBEDDED MARKDOWN DATA.*?═══ END EMBEDDED MARKDOWN DATA ═══ -->\n'
    if re.search(marker_re, html, re.DOTALL):
        html = re.sub(marker_re, embedded_block, html, count=1, flags=re.DOTALL)
    else:
        # Insert just before the main <script> block
        anchor = '\n  <script>\n    // ═══'
        html = html.replace(anchor, '\n' + embedded_block + '\n  <script>\n    // ═══', 1)

    # ── Update FILE_TREE ──
    tree_json = json.dumps(file_tree, indent=6)
    tree_re = r'const FILE_TREE = \{.*?\};'
    html = re.sub(tree_re, f'const FILE_TREE = {tree_json};', html, count=1, flags=re.DOTALL)

    with open(INDEX, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"  Done! Embedded {len(md_files)} markdown file(s) into index.html")
    print(f"  Updated FILE_TREE with {len(file_tree)} course(s):")
    for course, folders in file_tree.items():
        total = sum(len(files) for files in folders.values())
        print(f"    - {course}: {total} lecture(s)")
    print(f"\n  Open index.html in your browser — it works offline now!")


if __name__ == '__main__':
    build()
